baseURL = "https://pelicandev.io/"
languageCode = "en-us"
title = "PeliCanDev"
theme = "m10c"
paginate = 10
googleAnalytics = "UA-158097567-3"

[params]
  author = "Bartosz Pelikan"
  description = "Cloud Technology Enthusiast | .NET developer"
  avatar = "/images/img.jpg"

[[params.social]]
  name = "github"
  url = "https://github.com/bpelikan"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/bartoszpelikan"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/bartoszpelikan/"

[[params.social]]
  name = "mysite"
  url = "https://www.bartoszpelikan.pl/"
